#if !canImport(ObjectiveC)
import XCTest

extension DrStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DrStringTests = [
        ("testBadParameterFormat", testBadParameterFormat),
        ("testBadReturnsFormat", testBadReturnsFormat),
        ("testBadThrowsFormat", testBadThrowsFormat),
        ("testCompletelyDocumentedFunction", testCompletelyDocumentedFunction),
        ("testIgnoreThrows", testIgnoreThrows),
        ("testLowercaseKeywords", testLowercaseKeywords),
        ("testMisalignedParameterDescriptions", testMisalignedParameterDescriptions),
        ("testMissingSectionSeparator", testMissingSectionSeparator),
        ("testMissingStuff", testMissingStuff),
        ("testNoDocNoError", testNoDocNoError),
        ("testRedundantKeywords", testRedundantKeywords),
        ("testUppercaseKeywords", testUppercaseKeywords),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DrStringTests.__allTests__DrStringTests),
    ]
}
#endif
