#if !canImport(ObjectiveC)
import XCTest

extension ValidatingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidatingTests = [
        ("testCommonSequenceFindsEmptyForEmptySequence", testCommonSequenceFindsEmptyForEmptySequence),
        ("testCommonSequenceFindsLongestCommonSubsequence", testCommonSequenceFindsLongestCommonSubsequence),
        ("testCommonSequenceFindsStrictSubsequence", testCommonSequenceFindsStrictSubsequence),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ValidatingTests.__allTests__ValidatingTests),
    ]
}
#endif
