#if !canImport(ObjectiveC)
import XCTest

extension CLITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CLITests = [
        ("testCommandLineArgumentOverridesConfigFileOptionByExplicitNegation", testCommandLineArgumentOverridesConfigFileOptionByExplicitNegation),
        ("testCommandLineArgumentOverridesConfigFileOptionForCheckSubcommand", testCommandLineArgumentOverridesConfigFileOptionForCheckSubcommand),
        ("testCommandLineArgumentOverridesConfigFileOptionForFormatSubcommand", testCommandLineArgumentOverridesConfigFileOptionForFormatSubcommand),
        ("testConfigFileOptionsAreProperlyParsedForCheckSubcommand", testConfigFileOptionsAreProperlyParsedForCheckSubcommand),
        ("testConfigFileOptionsAreProperlyParsedForFormatSubcommand", testConfigFileOptionsAreProperlyParsedForFormatSubcommand),
        ("testEndLineIsProperlyParsed", testEndLineIsProperlyParsed),
        ("testStartLineIsProperlyParsed", testStartLineIsProperlyParsed),
    ]
}

extension EmptyPatternsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmptyPatternsTests = [
        ("testEmptyPatternForExclusionIsNotReportedWhenItsAllowed", testEmptyPatternForExclusionIsNotReportedWhenItsAllowed),
        ("testEmptyPatternForExclusionIsReportedWhenItsNotAllowed", testEmptyPatternForExclusionIsReportedWhenItsNotAllowed),
    ]
}

extension FormattingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FormattingTests = [
        ("testBug192", testBug192),
        ("testFormatHandlesEmptyDocstringItemsCorrectly", testFormatHandlesEmptyDocstringItemsCorrectly),
        ("testFormatPatchesFilesProperly0", testFormatPatchesFilesProperly0),
        ("testFormatPatchesFilesProperly1", testFormatPatchesFilesProperly1),
        ("testFormatPatchesFilesProperly2", testFormatPatchesFilesProperly2),
    ]
}

extension InvalidPatternTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvalidPatternTests = [
        ("testInvalidPatternForExclusionIsReported", testInvalidPatternForExclusionIsReported),
        ("testInvalidPatternForInclusionIsReported", testInvalidPatternForInclusionIsReported),
        ("testValidPatternForExclusionIsNotReported", testValidPatternForExclusionIsNotReported),
        ("testValidPatternForInclusionIsNotReported", testValidPatternForInclusionIsNotReported),
    ]
}

extension ProblemCheckingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProblemCheckingTests = [
        ("testAlignAfterColon", testAlignAfterColon),
        ("testAlignAfterColonNotRequired", testAlignAfterColonNotRequired),
        ("testBadParameterFormat", testBadParameterFormat),
        ("testBadParametersKeywordFormat", testBadParametersKeywordFormat),
        ("testBadReturnsFormat", testBadReturnsFormat),
        ("testBadThrowsFormat", testBadThrowsFormat),
        ("testCompletelyDocumentedFunction", testCompletelyDocumentedFunction),
        ("testGroupedParameterStyle", testGroupedParameterStyle),
        ("testIgnoreReturns", testIgnoreReturns),
        ("testIgnoreThrows", testIgnoreThrows),
        ("testInitProblemsAreChecked", testInitProblemsAreChecked),
        ("testInitThrowsIsNotRedundant", testInitThrowsIsNotRedundant),
        ("testLowercaseKeywords", testLowercaseKeywords),
        ("testMisalignedParameterDescriptions", testMisalignedParameterDescriptions),
        ("testMissingSectionSeparator", testMissingSectionSeparator),
        ("testMissingStuff", testMissingStuff),
        ("testNoDocNoError", testNoDocNoError),
        ("testProblemPositions", testProblemPositions),
        ("testRedundantKeywords", testRedundantKeywords),
        ("testRedundantKeywordsPathsOnly", testRedundantKeywordsPathsOnly),
        ("testSeparateLineInThrowsIsNotTreatedAsContinuedBody", testSeparateLineInThrowsIsNotTreatedAsContinuedBody),
        ("testSeparateParameterStyle", testSeparateParameterStyle),
        ("testThrowsWithDescriptionStartingFromNextLine", testThrowsWithDescriptionStartingFromNextLine),
        ("testUppercaseKeywords", testUppercaseKeywords),
        ("testWhateverParameterStyle", testWhateverParameterStyle),
    ]
}

extension SuperfluousExclusionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SuperfluousExclusionTests = [
        ("testAllowSuperfluousExclusion", testAllowSuperfluousExclusion),
        ("testNormalExclusionIsNotSuperfluous", testNormalExclusionIsNotSuperfluous),
        ("testNoSuperfluousExclusion", testNoSuperfluousExclusion),
        ("testSuperfluousExclusionBecauseItsNotIncludedToBeginWith", testSuperfluousExclusionBecauseItsNotIncludedToBeginWith),
        ("testSuperfluousExclusionViaGlob", testSuperfluousExclusionViaGlob),
        ("testYesSuperfluousExclusion", testYesSuperfluousExclusion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CLITests.__allTests__CLITests),
        testCase(EmptyPatternsTests.__allTests__EmptyPatternsTests),
        testCase(FormattingTests.__allTests__FormattingTests),
        testCase(InvalidPatternTests.__allTests__InvalidPatternTests),
        testCase(ProblemCheckingTests.__allTests__ProblemCheckingTests),
        testCase(SuperfluousExclusionTests.__allTests__SuperfluousExclusionTests),
    ]
}
#endif
