#if !canImport(ObjectiveC)
import XCTest

extension AlignmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlignmentTests = [
        ("testContinuationLineWithOneSpaceIndentMissingForVerticalAlign", testContinuationLineWithOneSpaceIndentMissingForVerticalAlign),
    ]
}

extension ParametersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParametersTests = [
        ("testMissingColonInHeaderIsReported", testMissingColonInHeaderIsReported),
        ("testMissingColonInParameterEntryIsReported", testMissingColonInParameterEntryIsReported),
    ]
}

extension ReturnsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReturnsTests = [
        ("testAlignAfterColonIsNotAProblem", testAlignAfterColonIsNotAProblem),
        ("testAlignBeforeColonIsAProblem", testAlignBeforeColonIsAProblem),
        ("testMissingColonIsAProblem", testMissingColonIsAProblem),
    ]
}

extension ThrowsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThrowsTests = [
        ("testAlignAfterColonIsNotAProblem", testAlignAfterColonIsNotAProblem),
        ("testAlignBeforeColonIsAProblem", testAlignBeforeColonIsAProblem),
        ("testMissingColonIsAProblem", testMissingColonIsAProblem),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlignmentTests.__allTests__AlignmentTests),
        testCase(ParametersTests.__allTests__ParametersTests),
        testCase(ReturnsTests.__allTests__ReturnsTests),
        testCase(ThrowsTests.__allTests__ThrowsTests),
    ]
}
#endif
