#if !canImport(ObjectiveC)
import XCTest

extension ReturnsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReturnsTests = [
        ("testAlignAfterColonIsNotAProblem", testAlignAfterColonIsNotAProblem),
        ("testAlignBeforeColonIsAProblem", testAlignBeforeColonIsAProblem),
    ]
}

extension ThrowsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThrowsTests = [
        ("testAlignAfterColonIsNotAProblem", testAlignAfterColonIsNotAProblem),
        ("testAlignBeforeColonIsAProblem", testAlignBeforeColonIsAProblem),
    ]
}

extension ValidatingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidatingTests = [
        ("testCommonSequenceFindsEmptyForEmptySequence", testCommonSequenceFindsEmptyForEmptySequence),
        ("testCommonSequenceFindsLongestCommonSubsequence", testCommonSequenceFindsLongestCommonSubsequence),
        ("testCommonSequenceFindsStrictSubsequence", testCommonSequenceFindsStrictSubsequence),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ReturnsTests.__allTests__ReturnsTests),
        testCase(ThrowsTests.__allTests__ThrowsTests),
        testCase(ValidatingTests.__allTests__ValidatingTests),
    ]
}
#endif
