name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        action:
          - build
          - package-darwin
          - test
          - test-generated-artifacts
    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    - name: Action
      run: make ${{ matrix.action }}

  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.0.3
          - 5.1.1
        ubuntu:
          - xenial
          - bionic
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v1
    - name: Action
      run: Scripts/ubuntu.sh ${{ matrix.action }} ${{ matrix.swift }} ${{ matrix.ubuntu }}
