name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.app
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Test Linux manifest
      run: make test-generate-linux-manifests

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build-docker
    - name: Test
      run: make test-docker
