name: Continuous Integration

on: [push, pull_request]

jobs:
  macos-build:
    name: macOS Build
    runs-on: macOS-latest
    strategy:
      matrix:
        developer_dir: [
          "/Applications/Xcode_11.app"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        DEVELOPER_DIR: "${{ matrix.developer_dir }}/Contents/Developer"
      run: make build

  macos-test:
    name: macOS Test
    runs-on: macOS-latest
    strategy:
      matrix:
        developer_dir: [
          "/Applications/Xcode_11.app"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: test
      env:
        DEVELOPER_DIR: "${{ matrix.developer_dir }}/Contents/Developer"
      run: |
          make test
          make test-generate-linux-manifests

  docker-test:
    name: Docker Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test-docker
      run: make test-docker

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build-docker
      run: make build-docker
