name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12.3
        action:
          - build
          - package-darwin
          - test
          - test-generated-artifacts
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Action
      run: make ${{ matrix.action }}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.3.2
        ubuntu:
          - bionic
          - focal
        action:
          - build
          - test
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: Scripts/ubuntu.sh ${{ matrix.action }} ${{ matrix.swift }} ${{ matrix.ubuntu }}
