name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    - name: Build
      run: make build
    - name: Package
      run: make package-darwin
    - name: Test
      run: make test
    - name: Test generated artifacts
      run: make test-generated-artifacts

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build-docker
    - name: Test
      run: make test-docker
