name: Continuous Integration

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        action:
          - build
          - package-darwin
          - test
          - test-generated-artifacts
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Action
      run: make ${{ matrix.action }}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu:
          - docker: amd64
            release: focal
          - docker: amd64
            release: bionic
          #- docker: arm64/v8
          #  release: focal
        swift:
          - 5.6
        action:
          - build
          - package-ubuntu
          - test
    steps:
    - uses: actions/checkout@v2
    - name: Action
      run: Scripts/ubuntu.sh ${{ matrix.action }} ${{ matrix.swift }} ${{ matrix.ubuntu.release }} ${{ matrix.ubuntu.docker }}
